name: 'Greet Action'
description: 'Greet the specified person/people'
inputs:
  names:
    description: 'Names of the people to greet'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Print Greeting
      run: |
        echo "Hello, ${{ inputs.names }}!"
      shell: bash