name: 'Greet Action'
description: 'Greet the specified person/people'
inputs:
  names:
    description: 'Names of the people to greet'
    required: true
outputs:
  greeted_names:
    description: 'Names of the people greeted'
runs:
  using: 'composite'
  steps:
    - name: Print Greeting
      id: print_greeting
      run: |
        echo "Hello, ${{ inputs.names }}!"
        echo "greeted_names=${{ inputs.names }}" >> $GITHUB_OUTPUT
      shell: bash
