name: Cron and Action Workflow-ex6

on: push
  # schedule:
  #   - cron: '*/5 * * * *' # Every 5 minutes

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run Greet Action
      uses: ./.github/actions/greet.yaml
      with:
        names: 'Engineers'