name: Cron and Action Workflow-ex6

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes

    steps:
      - uses: actions/checkout@v4
      - name: Run Greet Action
        id: greet_step
        uses: ./.github/actions/greet_people
        with:
          names: 'Engineers'
      - name: Conditional Step that should succeed
        if: ${{ steps.greet_step.outputs.greeted_names == 'Engineers and 1 more person' }}
        run: echo "Conditional step"

      - name: Set boolean output
        run: |
          if [[ "${{ steps.greet_step.outputs.greeted_names }}" == "Engineers and 1 more person" ]]; then
            echo "SHOULD_RUN=true" >> $GITHUB_ENV
          else
            echo "SHOULD_RUN=false" >> $GITHUB_ENV
          
      - name: Conditional Step that should succeed
        if: ${{ env.SHOULD_RUN == 'true' }}
        run: echo "Conditional step is running because the condition is met"

      - name: Another Step that runs if the boolean is true
        if: ${{ env.SHOULD_RUN == 'true' }}
        run: echo "Another step is also running because the condition is met"
