name: Stress Test Workflow

on: push

jobs:
  stress-test:
    runs-on: high-powered-pc

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install stress-ng
      run: sudo apt-get update && sudo apt-get install -y stress-ng

    - name: Run stress-ng
      run: |
        echo "Starting stress test"
        stress-ng --cpu 8 --io 8 --vm 8 --vm-bytes 7G --timeout 300s --metrics-brief




