name: Cron and Action Workflow-ex6

on: push

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run Greet Action
        id: greet_step
        uses: ./.github/actions/greet_people
        with:
          names: 'Engineers'
      - name: Conditional Step that should succeed
        if: ${{ steps.greet_step.outputs.greeted_names == 'Engineers and 1 more person' }}
        run: echo "Conditional step"

      - name: debug step
        run: echo "greeted_names ${{ steps.greet_step.outputs.greeted_names }}"

      - name: Set boolean output
        id: set_boolean
        run: |
          if [[ "${{ steps.greet_step.outputs.greeted_names }}" == 'Engineers and 1 more person' ]]; then
            echo "SHOULD_RUN=true" >> $GITHUB_ENV
          else
            echo "SHOULD_RUN=false" >> $GITHUB_ENV
          fi
        shell: bash
          
      # Conditional step based on the boolean value
      - name: Conditional Step that should succeed
        if: ${{ steps.set_boolean.outputs.SHOULD_RUN == 'true' }}
        run: echo "Conditional step is running because the condition is met"
