name: Test and Update Badge

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        pytest --junitxml=result.xml exercise_2
      continue-on-error: true

    - name: Check test result
      id: check
      run: |
        if grep -q "<failure" result.xml; then
          echo "::set-output name=status::failing"
        else
          echo "::set-output name=status::passing"
        fi

    - name: Update README with badge
      run: |
        if [ "${{ steps.check.outputs.status }}" = "passing" ]; then
          badge_url="https://img.shields.io/badge/tests-passing-brightgreen"
        else
          badge_url="https://img.shields.io/badge/tests-failing-red"
        fi
        sed -i 's|!\[Test Status\](.*)|![Test Status]('"$badge_url"')|g' README.md

    - name: Commit updated README
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Update test status badge [skip ci]"
        git push origin HEAD:master
      if: always()