name: Cron and Action Workflow-ex6

on: push

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run Greet Action
        id: greet_step
        uses: ./.github/actions/greet_people
        with:
          names: 'Engineers'
      - name: Debug Step
        run: echo "Greeted names ${{ steps.greet_step.outputs.greeted_names }}"
      - name: Conditional Step
        if: ${{ steps.greet_step.outputs.greeted_names == 'Engineers and 1 more person' }}
        run: echo "Conditional step"
